dist: xenial
sudo: false

branches:
    only:
        - travis

language: python

matrix:
    include:
        - python: 3.5
          env: TOXENV=py35-pyqt571
        - python: 3.6
          env: TOXENV=py36-pyqt511
        - python: 3.7
          env: TOXENV=py37-pyqt511-cov
        - python: 3.7
          env: TOXENV=lint

install:
    - pip install tox

script:
    - tox
